 * Serving Flask app 'dms'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5055
 * Running on http://10.99.115.211:5055
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
10.99.115.211 - - [26/Feb/2023 17:43:05] "POST /get-bkc-id HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 17:44:39] "GET /get-provisioner HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 17:45:39] "POST /get-keys HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 17:46:11] "GET /device-updater HTTP/1.1" 200 -
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/device_update_manager.py', reloading
{'platform': 'ADL-PS', 'guid': 'cdc08935-9e97-4e5b-9ab6-94d5e5c4aa26', 'profile': 'RT'}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/experiment.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/experiment.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/experiment.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/device_update_manager.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
10.99.115.211 - - [26/Feb/2023 21:17:16] "POST /get-bkc-id HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 21:18:03] "GET /get-provisioner HTTP/1.1" 200 -
 * Detected change in '/home/rudra/Documents/Provisioner/scripts/provisioner.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
10.99.115.134 - - [26/Feb/2023 21:19:32] "GET /get-provisioner HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 21:19:41] "POST /get-keys HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 21:21:03] "GET /get-provisioner HTTP/1.1" 200 -
10.99.115.134 - - [26/Feb/2023 21:21:20] "[35m[1mPOST /get-keys HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rudra/Documents/Provisioner/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/rudra/Documents/Provisioner/dms.py", line 53, in getKeys
    keys['thingsboard-host'] = THINGSBOARD_HOST
TypeError: 'NoneType' object does not support item assignment
 * Detected change in '/home/rudra/Documents/Provisioner/dms.py', reloading
{'platform': 'ADL-PS', 'guid': 'cdc08935-9e97-4e5b-9ab6-94d5e5c4aa26', 'profile': 'RT'}
{'platform': 'ADL-PS', 'guid': 'cdc08935-9e97-4e5b-9ab6-94d5e5c4aa26', 'profile': 'AUTO UPDATE DKAM SERVICE CREATEDRT'}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 375-197-788
